name: Godot CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.1.stable ~/.local/share/godot/export_templates/4.7.1.stable
        
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --export-release "Web" build/web/index.html
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-pwa
          path: build/web

  export-android:
    name: Android Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.1.stable ~/.local/share/godot/export_templates/4.7.1.stable
          
      - name: Create debug keystore
        run: |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          
      - name: Setup Android Export Preset
        run: |
          sed -i "s|keystore/debug=\"\"|keystore/debug=\"debug.keystore\"|g" export_presets.cfg
          sed -i "s|keystore/debug_user=\"\"|keystore/debug_user=\"androiddebugkey\"|g" export_presets.cfg
          sed -i "s|keystore/debug_password=\"\"|keystore/debug_password=\"android\"|g" export_presets.cfg

      - name: Android Build
        run: |
          mkdir -v -p build/android
          godot --headless --export-debug "Android" build/android/Cricket8Bit.apk
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android/Cricket8Bit.apk
